package main

type Template struct {
	ID          string
	Name        string
	Description string
	RootName    string
	Nodes       []TreeNode
}

var templates = []Template{
	{
		ID: "nextjs", Name: "Next.js App", Description: "Full-stack Next.js with App Router",
		RootName: "my-app",
		Nodes: []TreeNode{
			newFolder("src",
				newFolder("app",
					newFolder("api", newFolder("health", newFile("route.ts"))),
					newFile("layout.tsx"), newFile("page.tsx"), newFile("globals.css"),
				),
				newFolder("components", newFolder("ui", newFile("button.tsx"), newFile("input.tsx"))),
				newFolder("lib", newFile("utils.ts"), newFile("db.ts")),
				newFolder("hooks", newFile("use-auth.ts")),
				newFolder("types", newFile("index.ts")),
			),
			newFolder("public", newFile("favicon.ico")),
			newFile("package.json"), newFile("tsconfig.json"), newFile("next.config.ts"),
			newFile(".env.example"), newFile(".gitignore"), newFile("README.md"),
		},
	},
	{
		ID: "python", Name: "Python Project", Description: "Python package with tests and docs",
		RootName: "my-package",
		Nodes: []TreeNode{
			newFolder("src",
				newFolder("my_package",
					newFile("__init__.py"), newFile("main.py"), newFile("config.py"),
					newFolder("models", newFile("__init__.py"), newFile("user.py")),
					newFolder("services", newFile("__init__.py"), newFile("auth.py")),
					newFolder("utils", newFile("__init__.py"), newFile("helpers.py")),
				),
			),
			newFolder("tests",
				newFile("conftest.py"), newFile("test_main.py"),
				newFolder("services", newFile("test_auth.py")),
			),
			newFolder("docs", newFile("index.md")),
			newFile("pyproject.toml"), newFile("requirements.txt"),
			newFile(".env.example"), newFile(".gitignore"), newFile("README.md"),
		},
	},
	{
		ID: "react-lib", Name: "React Library", Description: "Publishable React component package",
		RootName: "my-ui-lib",
		Nodes: []TreeNode{
			newFolder("src",
				newFolder("components", newFile("Button.tsx"), newFile("Input.tsx"), newFile("Modal.tsx"), newFile("Card.tsx")),
				newFolder("hooks", newFile("useToggle.ts"), newFile("useClickOutside.ts")),
				newFile("index.ts"),
			),
			newFolder("__tests__", newFile("Button.test.tsx")),
			newFolder("dist"),
			newFile("package.json"), newFile("tsconfig.json"), newFile("vite.config.ts"),
			newFile(".gitignore"), newFile("README.md"),
		},
	},
	{
		ID: "go", Name: "Go Service", Description: "Go microservice with standard layout",
		RootName: "my-service",
		Nodes: []TreeNode{
			newFolder("cmd", newFolder("server", newFile("main.go"))),
			newFolder("internal",
				newFolder("handler", newFile("health.go"), newFile("user.go")),
				newFolder("service", newFile("user.go")),
				newFolder("repository", newFile("user.go")),
				newFolder("model", newFile("user.go")),
				newFolder("config", newFile("config.go")),
			),
			newFolder("pkg", newFile("response.go")),
			newFolder("migrations"),
			newFile("go.mod"), newFile("Makefile"), newFile("Dockerfile"),
			newFile(".gitignore"), newFile("README.md"),
		},
	},
	{
		ID: "generic", Name: "Generic Project", Description: "Basic structure for any project",
		RootName: "my-project",
		Nodes: []TreeNode{
			newFolder("src", newFile("index.ts")),
			newFolder("docs", newFile("README.md")),
			newFolder("tests", newFile("index.test.ts")),
			newFile("package.json"), newFile(".gitignore"), newFile("README.md"),
		},
	},
	{
		ID: "llm-wiki", Name: "LLM Wiki", Description: "Karpathy-style knowledge wiki",
		RootName: "llm-wiki",
		Nodes: []TreeNode{
			newFolder("raw", newFolder("domain-1"), newFolder("domain-2"), newFolder("assets")),
			newFolder("wiki",
				newFile("index.md"), newFile("log.md"), newFile("overview.md"),
				newFolder("domain-1", newFile("overview.md"), newFolder("sources"), newFolder("concepts"), newFolder("entities")),
				newFolder("domain-2", newFile("overview.md"), newFolder("sources"), newFolder("concepts"), newFolder("entities")),
				newFolder("shared"),
			),
			newFolder("sessions", newFolder("exports"), newFolder("confidential"), newFolder("wiki-digests")),
			newFile("AGENTS.md"), newFile(".gitignore"), newFile("README.md"),
		},
	},
	{
		ID: "weekly", Name: "Weekly Calendar", Description: "Year organized by week number",
		RootName: "2026",
		Nodes: []TreeNode{
			newFolder("Q1",
				newFolder("W01", newFile("notes.md")), newFolder("W02", newFile("notes.md")),
				newFolder("W03", newFile("notes.md")), newFolder("W04", newFile("notes.md")),
				newFolder("W05", newFile("notes.md")), newFolder("W06", newFile("notes.md")),
				newFolder("W07", newFile("notes.md")), newFolder("W08", newFile("notes.md")),
				newFolder("W09", newFile("notes.md")), newFolder("W10", newFile("notes.md")),
				newFolder("W11", newFile("notes.md")), newFolder("W12", newFile("notes.md")),
				newFolder("W13", newFile("notes.md")),
			),
			newFolder("Q2",
				newFolder("W14", newFile("notes.md")), newFolder("W15", newFile("notes.md")),
				newFolder("W16", newFile("notes.md")), newFolder("W17", newFile("notes.md")),
				newFolder("W18", newFile("notes.md")), newFolder("W19", newFile("notes.md")),
				newFolder("W20", newFile("notes.md")), newFolder("W21", newFile("notes.md")),
				newFolder("W22", newFile("notes.md")), newFolder("W23", newFile("notes.md")),
				newFolder("W24", newFile("notes.md")), newFolder("W25", newFile("notes.md")),
				newFolder("W26", newFile("notes.md")),
			),
			newFolder("Q3",
				newFolder("W27", newFile("notes.md")), newFolder("W28", newFile("notes.md")),
				newFolder("W29", newFile("notes.md")), newFolder("W30", newFile("notes.md")),
				newFolder("W31", newFile("notes.md")), newFolder("W32", newFile("notes.md")),
				newFolder("W33", newFile("notes.md")), newFolder("W34", newFile("notes.md")),
				newFolder("W35", newFile("notes.md")), newFolder("W36", newFile("notes.md")),
				newFolder("W37", newFile("notes.md")), newFolder("W38", newFile("notes.md")),
				newFolder("W39", newFile("notes.md")),
			),
			newFolder("Q4",
				newFolder("W40", newFile("notes.md")), newFolder("W41", newFile("notes.md")),
				newFolder("W42", newFile("notes.md")), newFolder("W43", newFile("notes.md")),
				newFolder("W44", newFile("notes.md")), newFolder("W45", newFile("notes.md")),
				newFolder("W46", newFile("notes.md")), newFolder("W47", newFile("notes.md")),
				newFolder("W48", newFile("notes.md")), newFolder("W49", newFile("notes.md")),
				newFolder("W50", newFile("notes.md")), newFolder("W51", newFile("notes.md")),
				newFolder("W52", newFile("notes.md")),
			),
			newFolder("archive"),
			newFile("README.md"),
		},
	},
}
