import { NextRequest, NextResponse } from 'next/server'

interface TreeNode {
  name: string
  type: 'folder' | 'file'
  children: TreeNode[]
}

interface ScriptRequest {
  rootName: string
  nodes: TreeNode[]
  sourcePath?: string // Original directory path
}

function generateCommands(
  nodes: TreeNode[],
  rootName: string,
  sourcePath: string,
  currentPath: string = ''
): string[] {
  const lines: string[] = []

  for (const node of nodes) {
    const relativePath = currentPath ? `${currentPath}/${node.name}` : node.name

    if (node.type === 'folder') {
      lines.push(`mkdir -p "${rootName}/${relativePath}"`)
      if (node.children.length > 0) {
        lines.push(...generateCommands(node.children, rootName, sourcePath, relativePath))
      }
    } else {
      const src = `${sourcePath}/${relativePath}`
      const dst = `${rootName}/${relativePath}`
      // Only move if source exists (user will edit path)
      lines.push(`if [ -f "${src}" ]; then mv "${src}" "${dst}"; else echo "MISSING: ${src}"; fi`)
    }
  }

  return lines
}

function generateCleanup(
  nodes: TreeNode[],
  sourcePath: string,
  currentPath: string = ''
): string[] {
  const lines: string[] = []

  for (const node of nodes) {
    const relativePath = currentPath ? `${currentPath}/${node.name}` : node.name
    const fullPath = `${sourcePath}/${relativePath}`

    if (node.type === 'folder') {
      if (node.children.length > 0) {
        lines.push(...generateCleanup(node.children, sourcePath, relativePath))
      }
      lines.push(`rmdir "${fullPath}" 2>/dev/null || true`)
    }
  }

  return lines
}

function generateDryRun(
  nodes: TreeNode[],
  rootName: string,
  currentPath: string = '',
  prefix: string = ''
): string[] {
  const lines: string[] = []

  for (const node of nodes) {
    const relativePath = currentPath ? `${currentPath}/${node.name}` : node.name

    if (node.type === 'folder') {
      lines.push(`${prefix}[DIR]  ${rootName}/${relativePath}`)
      if (node.children.length > 0) {
        lines.push(...generateDryRun(node.children, rootName, relativePath, prefix + '  '))
      }
    } else {
      lines.push(`${prefix}[FILE] ${rootName}/${relativePath}`)
    }
  }

  return lines
}

export async function POST(req: NextRequest) {
  try {
    const { rootName, nodes, sourcePath = '/path/to/source' } = await req.json()

    if (!rootName || !Array.isArray(nodes)) {
      return NextResponse.json({ error: 'rootName and nodes[] required' }, { status: 400 })
    }

    const safeRoot = rootName.replace(/[^a-zA-Z0-9_-]/g, '_')

    const lines: string[] = [
      '#!/bin/bash',
      '#',
      `# Directory Reorganization Script`,
      `# Generated by Tree Architect`,
      `#`,
      `# BEFORE RUNNING:`,
      `# 1. Review this script carefully`,
      `# 2. Set SOURCE_PATH to your actual source directory`,
      `# 3. Run with: bash reorganize.sh`,
      `#`,
      `set -euo pipefail`,
      ``,
      `SOURCE_PATH="${sourcePath}"`,
      `TARGET_ROOT="${safeRoot}"`,
      ``,
      `echo "=== DRY RUN ==="`,
      `echo "Target structure:"`,
      ...generateDryRun(nodes, safeRoot).map(l => `echo "${l}"`),
      ``,
      `echo ""`,
      `echo "Press Enter to continue or Ctrl+C to abort..."`,
      `read -r`,
      ``,
      `echo "=== CREATING TARGET STRUCTURE ==="`,
      ...generateCommands(nodes, safeRoot, '${SOURCE_PATH}'),
      ``,
      `echo "=== CLEANUP EMPTY DIRS ==="`,
      ...generateCleanup(nodes, '${SOURCE_PATH}'),
      ``,
      `echo "Done. Review ${safeRoot}/ for results."`,
    ]

    return NextResponse.json({
      script: lines.join('\n'),
      filename: `reorganize-${safeRoot}.sh`,
    })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
